### ISSUE TITLE
Parent / child module : access parent settings from child

### ISSUE THREAD

**Issue by MarieComet** [elegantthemes/create-divi-extension#110]
### Problem Description

I've a parent / child module, I need to access parent module settings from child module in `get_fields` function.
I've tried to create a global variable in the parent `before_render` function, but in my child module, `get_fields` is called to soon, so my variable is empty.
I found the `get_parent_modules` function but I don't know how to use it.
Is there any way to access parent settings from child ? It seem to be a very basic feature...

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by jcdotnet** [comment]
Hello @MarieComet, I was tried that with no luck either. 

I want to show / hide items fields depending on a parent field, for example:

PARENT:

```
public function get_fields() {
		return array(
			'element' => array(
				'label'           	=> esc_html__( 'Element', 'plugin_domain' ),
				'type'            	=> 'select',
				'option_category' 	=> 'configuration',
				'options'         	=> array(
					'optA' 	=> esc_html__( 'Circle', 'plugin_domain' ),
					'optB'  	=> esc_html__( 'Square', 'plugin_domain' ),
					'optC'  	=> esc_html__( 'Triangle', 'plugin_domain' )
				),
			),
                        ....
```
CHILD:

```
public function get_fields() {
		return array(
			'triangle_option' => array(
				'label'           	=> esc_html__( 'Enter the triangle...', 'plugin_domain' ),
				'type'            	=> 'text',
				'show_if'           => array( 'element' => 'optC') // I want this field to be dependet
			),
                        ...
```
This would be very useful for third-party modules and I don't know if it's possible, if not I suggest these dependencies as a improvement.

**Comment by MarieComet** [comment]
@jcdotnet that's exactly what I'm trying to do

**Comment by lots0logs** [comment]
>I want to show / hide items fields depending on a parent field, for example:

The ability to do that was added very recently. Its not documented yet. Here's how you would do it with your example:
```
public function get_fields() {
  return array(
	'triangle_option' => array(
		'label'   => esc_html__( 'Enter the triangle...', 'plugin_domain' ),
		'type'    => 'text',
		'show_if'   => array( 'parentModule:element' => 'optC') // I want this field to be dependent
	),
        ...
```

Hope that helps :smiley:

**Comment by MarieComet** [comment]
Awesome ! Thanks you!

**Comment by jcdotnet** [comment]
@lots0logs How recently was it added? I'm testing with Divi 3.3.1 and it seems not work for me. I will get back to this later and let you know is something is wrong. BTW I was looking forward to this feature, I'm glad you have finally added it :) thank you!

**Comment by MarieComet** [comment]
Same here, not working.
@lots0logs maybe when you write `'parentModule:element' => 'optC'`, `parentModule` should be replaced with parent slug, or class name ?
I've tried both, child field which should be affected not showing at all.

**Comment by lots0logs** [comment]
IIRC, it was added in 3.4. Let me know if you still have trouble when using 3.4 or later. Also note this only works in the VB currently.

**Comment by MarieComet** [comment]
Ok, I didn't see that Divi was updated.
I can't test now because as I said [here](https://github.com/elegantthemes/create-divi-extension/issues/69) I'm not able to use the developement mode, and debugging the VB... Using `yarn build` when developing is really not suitable

**Comment by lots0logs** [comment]
Noted. I'm going to look into the issue with yarn start asap.

**Comment by jdurnil** [comment]
It is not working for me what code would would i need to just grab a value from a text or say range slider
like this for parent element
`'num_rows' => array(
      'default'         => '0',
      'label'           => esc_html__( 'Number of Rows', 'etl-divilocal' ),
      'type'            => 'range',
      'range_settings'  => array(
              'min'         => '1',
               'max'         => '6'
        ),
       'option_category' => 'basic_option',
       'description'     => esc_html__( 'Enter in desired number of rows.', 'etl-divilocal' ),
       'toggle_slug'     => 'main_content',
),
`
and this for child element trying to get value from parent
` 'rows_span' => array(
                'default'         => '0',
                'label'           => esc_html__( 'Rows to Span', 'etl-divilocal' ),
                'type'            => 'range',
                'range_settings'  => array(
                    'min'         => '1',
                    'max'         => 'parentModule:num_rows'

                ),
                'option_category' => 'basic_option',
                'description'     => esc_html__( 'Enter in desired number of rows.', 'etl-divilocal' ),
                'toggle_slug'     => 'main_content',
            ),`

**Comment by mrkenng** [comment]
I was trying this on the yes_no_button but could not get that to work on child.  Any ideas?

```
'elementchild' => array(
                'label'           => esc_html__( 'Text', 'et_builder' ),
                'type'            => 'text',
                'option_category' => 'basic_option',
                'toggle_slug'     => 'main_content',
                'show_if'         => array(
					'parentModule:parentelement' => 'on',
				),
            ),
```

**Comment by MarieComet** [comment]
@jdurnil @mrkenng 
Here is a working example : 

Parent : 
```
	public function get_fields() {
		return array(
			'show_option' => array(
				'label'           	=> esc_html__( 'Show option', 'plugin_domain' ),
				'type'            	=> 'yes_no_button',
				'option_category' 	=> 'configuration',
				'options'         	=> array(
					'off'  	=> esc_html__( 'Off', 'plugin_domain' ),
					'on' 	=> esc_html__( 'On', 'plugin_domain' ),
				),
				'toggle_slug'     => 'main_content',
				'tab_slug'		  => 'general',
			),
		);
	}
```
Child : 
```
	public function get_fields() {
		return array(
			'content' => array(
				'label'           => esc_html__( 'Content', 'mcdt-mc-divi-tutorial' ),
				'type'            => 'tiny_mce',
				'option_category' => 'basic_option',
				'description'     => esc_html__( 'Content entered here will appear inside the module.', 'mcdt-mc-divi-tutorial' ),
				'toggle_slug'     => 'main_content',
				'tab_slug'		  => 'general',
				// permet de récupérer la valeur de l'option 'show_option' du parent
				'show_if'   => array( 'parentModule:show_option' => 'on')
			),
		);
	}

```
As @lots0logs said : It's working only in the VB, not the classic editor, and you need Divi >= 3.4

**Comment by MarieComet** [comment]
@lots0logs now I'm looking for a way, in the VB, to set a state for each child, from a field parent value.
I've tried, in the [parent jsx](https://github.com/MarieComet/mc-divi-tutorial/blob/master/includes/modules/CompareTab/CompareTab.jsx) component : 
```
componentDidUpdate(lastProps, lastStates) {
    if( lastProps.show_option !== this.props.show_option ) {
      const showOption = this.props.content.map( ( content ) =>
        content.setState( { itemShowOption: this.props.show_option } )
      );
    }
  }
```
where `this.props.show_option` is a on/off yes_no_button field.
But `content.setState` always return `content.setState is not a function`

**Comment by jcdotnet** [comment]
Hey guys, it works in the page builder too!! (Divi 3.7). Trying to do the same with the advanced fields! I mean, advanced item fields depending on custom parent fields. 

Ok, as workaround I can make the advanced item field dependent on a new custom item field and use the show_if in that custom field, but I would like to do it the right way.

How would it be in my example if we had an advanced item field (font or whatever) which we want to show if 'element'  is 'optC'?

**Comment by jcdotnet** [comment]
@lots0logs this works in the VB as you said, but we can not use it because it throws the following exception in the console when editing in the backend: 

`'show_if'   => array( 'parentModule:element_from_parent' => 'optC')`

throws:

```
Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: element_from_parent
    at Function.ea.error (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,moxiejs,plupload&ver=5.2.1:2)
```

Is there a fix for this? Thank you!

**Comment by cedricDevWP** [comment]
Is it possible to implement this functionality for advanced fields (ex: ['fonts']) ?

here is an example of a case:

I have an on / off button allowing to display or not text in my module. If I check "no", the advanced fields to customize the text will be hidden. In my child element I would also like to show or hide these advanced fields according to the choice in the parent element.

I tried that : 

```php
$advanced_fields['fonts'] = array(
	'text' => array(
		'label'           => esc_html__( 'Text', 'et_builder' ),
		'hide_text_shadow' => true,
		'depends_show_if'	=> 'on',
		'depends_on'      => array(
		      'parentModule:show_text',
	        ),
	       'tab_slug'    => 'advanced',
	       'toggle_slug' => 'fonts',
	),
);

```

but not working.

**Comment by nexus-mediapark** [comment]
Hey, I'm actually interested if there is a way to get the parent field in to the render function so depending on the parent selection I would be able to switch template files displayed - cheers!

**Comment by nexus-mediapark** [comment]
Hey, so looks like this `parentModule:field` just won't work for me.

For some reason I can't store the data of the dependent field.
My code for parent:
`'slider_type'     => array(
                'label'           => esc_html__( 'Slider Type', 'eca-eca-divi-extension' ),
                'type'            => 'select',
                'option_category' => 'basic_option',
                'description'     => esc_html__( 'Select if the slider are either a textual slideshow or a video linked slideshow.', 'eca-eca-divi-extension' ),
                'toggle_slug'     => 'main_content',
                'options'         => array(
                    'text'  	=> esc_html__( 'Text Slider', 'eca-eca-divi-extension' ),
                    'video' 	=> esc_html__( 'Video Slider', 'eca-eca-divi-extension' ),
                )
            ),`
            
            My code for child:
            `
            'title'     => array( // Field Slug
                'label'           => esc_html__( 'Heading', 'eca-eca-divi-extension' ), // Field title/label
                'type'            => 'text', // Field type
                'option_category' => 'basic_option',
                'description'     => esc_html__( 'Input your desired heading here.', 'eca-eca-divi-extension' ), // Field Description
                'toggle_slug'     => 'main_content',
                'show_if'   => array( 'parentModule:slider_type' => 'text' ) // Field Dependency
            ),
            `
            
            So every time I'm adding a title to the child block the field data just won't store (after i save and refresh the field is empty).
            
            As well `var_dump($this->props['title'])` always gives me an empty string;
            
            Is there something I'm maybe missing?

**Comment by mvijay63** [comment]
Hey @nexus-mediapark , any update on this issue. I'm not able to update the settings when using `parentModule:field`. It always return the default value. 
Let me know if you found any workaround for this.
Thanks

**Comment by Lovely-Fellow** [comment]
> Hey @nexus-mediapark , any update on this issue. I'm not able to update the settings when using `parentModule:field`. It always return the default value. Let me know if you found any workaround for this. Thanks

I'm seeing same issue.
